<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.0-preview.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/dalenewman/JunkDrawer</RepositoryUrl>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageId>JunkDrawer.Autofac</PackageId>
    <Description>Transformalize Autofac integration for JunkDrawer.</Description>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../JunkDrawer/JunkDrawer.csproj" />
    <PackageReference Include="Autofac" Version="9.3.4" />
    <PackageReference Include="Cfg-NET.Reader" Version="1.0.1" />
    <PackageReference Include="Transformalize.Container.Autofac" Version="1.5.2" />
    <PackageReference Include="Transformalize.Provider.CsvHelper.Autofac" Version="1.5.1" />
    <PackageReference Include="Transformalize.Provider.Excel" Version="1.5.0" />
    <PackageReference Include="Transformalize.Provider.Sqlite.Autofac" Version="1.5.0" />
    <PackageReference Include="Transformalize.Provider.SqlServer.Autofac" Version="1.5.0" />
    <PackageReference Include="Transformalize.Provider.PostgreSql.Autofac" Version="1.5.0" />
    <PackageReference Include="Transformalize.Provider.MySql.Autofac" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Bootstrapper.cs" />
    <Compile Include="AutofacJunkBootstrapperFactory.cs" />
    <Compile Include="AppDataFolder.cs" />
    <Compile Include="Modern/*.cs" />
    <None Include="../LICENSE.md" Pack="true" PackagePath="" />
    <None Include="../docs/package-readme.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
