<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Test" />
    <ProjectReference Include="../JunkDrawer.Autofac/JunkDrawer.Autofac.csproj" />
    <PackageReference Include="Eto.Forms" Version="2.11.0" />
    <PackageReference Include="Hogimn.Sql.Formatter" Version="2.0.4" />
    <Compile Include="ModernMainForm.cs" />
    <Compile Include="ArrangementXml.cs" />
    <Compile Include="RecentFiles.cs" />
    <Compile Include="GuiLaunchOptions.cs" />
    <Compile Include="GuiStartup.cs" />
    <EmbeddedResource Include="Images/first.png" />
    <EmbeddedResource Include="Images/previous.png" />
    <EmbeddedResource Include="Images/next.png" />
    <EmbeddedResource Include="Images/last.png" />
    <EmbeddedResource Include="Images/sql.png" />
    <EmbeddedResource Include="Images/log.png" />
    <EmbeddedResource Include="Images/xml.png" />
  </ItemGroup>
</Project>
