<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>jd</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../JunkDrawer.Autofac/JunkDrawer.Autofac.csproj" />
    <Compile Include="Program.cs" />
    <Compile Include="Options.cs" />
    <Compile Include="CliLogger.cs" />
    <None Update="default.xml;mysql.xml;postgres.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="sqlite.xml" TargetPath="Examples/sqlite.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Files/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
