<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>jdgui</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../JunkDrawer.Eto.Core/JunkDrawer.Eto.Core.csproj" />
    <PackageReference Include="Eto.Platform.Windows" Version="2.11.0" />
    <Compile Include="Program.cs" />
    <None Update="sqlite.xml" TargetPath="Examples/sqlite.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
