<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>2.0.0-preview.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/dalenewman/JunkDrawer</RepositoryUrl>
    <PackageId>JunkDrawer</PackageId>
    <Description>Import delimited and Excel files into a database.</Description>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cfg-NET" Version="1.0.1" />
    <PackageReference Include="Transformalize" Version="1.5.2" />
    <PackageReference Include="Transformalize.Provider.Ado" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
    <None Include="../LICENSE.md" Pack="true" PackagePath="" />
    <None Include="../docs/package-readme.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
